name: Main workflow
on: [push]
jobs:
  all:
    env:
      DATABASE_URL: postgresql://postgres:@localhost:5432/trpcdb
      NODE_ENV: test
      NEXTAUTH_SECRET: supersecret
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['16.x']
        os: [ubuntu-latest]
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: trpcdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      - run: yarn lint
      - run: yarn build
